/* dsh-tweaks client bundle — generated by scripts/wrap-client.mjs */
window.__ModuleLoader__.load({
  id: "dsh-tweaks",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
//#region \0rolldown/runtime.js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
		key = keys[i];
		if (!__hasOwnProp.call(to, key) && key !== except) __defProp(to, key, {
			get: ((k) => from[k]).bind(null, key),
			enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
		});
	}
	return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(isNodeMode || !mod || !mod.__esModule || !__hasOwnProp.call(mod, "default") ? __defProp(target, "default", {
	value: mod,
	enumerable: true
}) : target, mod));
//#endregion
let react = require("react");
react = __toESM(react, 1);
let _deepseek_ai_dsh_client_ui_primitives = require("@deepseek-ai/dsh-client-ui-primitives");
//#region src/shared/constants.ts
/** The model-catalog namespace the image-input panel edits. */
const LLM_PI_AI_NS = "llm-pi-ai";
/**
* The one HTTP endpoint the browser half calls.
*
* A static client package is a prebuilt `__ModuleLoader__` bundle: it gets a
* `require` shim and nothing else, so the dynamic-half closure symbols
* (`host`, `styles`, `harness`) do not exist for it. The package therefore
* bridges to its own Host half the way every out-of-repository web plugin
* does — a `/api/...` route registered by the Host half.
*/
const RPC_PATH = "/api/dsh-tweaks/rpc";
/** Client-to-Host RPC method names. */
const RPC = {
	READ_CATALOG: "read-catalog",
	SET_IMAGE: "set-image",
	READ_INSTRUCTION: "read-instruction",
	WRITE_INSTRUCTION: "write-instruction"
};
//#endregion
//#region src/client/index.tsx
/**
* dsh-tweaks client half.
*
* Two settings surfaces, both writing through the package's own Host route:
* an image-input panel on each model provider card, and a Personalization
* section holding the general system instruction.
*
* A static client bundle is evaluated with only a `require` shim — the
* `host`/`styles` closure symbols belong to dynamic halves (source evaluated
* through `new Function`), so this half talks to its Host through `fetch` and
* owns its own style tag.
*/
/** Call one Host handler of this package; rejects with the Host's message. */
async function rpc(method, args = null) {
	const response = await fetch(RPC_PATH, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({
			method,
			args
		}),
		cache: "no-store"
	});
	const payload = await response.json().catch(() => null);
	if (!response.ok || payload === null || typeof payload !== "object" || payload.ok !== true) throw new Error(payload !== null && typeof payload === "object" && typeof payload.message === "string" ? payload.message : `请求失败（${response.status}）`);
	return payload.result ?? null;
}
/** Own the package stylesheet: no `styles` builtin exists for a static bundle. */
function insertStyles(css) {
	const tag = document.createElement("style");
	tag.dataset.plugin = "dsh-tweaks";
	tag.textContent = css;
	document.head.appendChild(tag);
	return () => tag.remove();
}
const SYSTEM_INSTRUCTION_SECTION_ID = "dsh-tweaks-personalization";
/** How many rows stay visible while collapsed; the next one is half-masked. */
const VISIBLE_ROWS = 3.5;
const ROW_HEIGHT = 32;
function ImageInputPanel({ providerId, invalidations }) {
	useInvalidationVersion(invalidations);
	const [catalog, setCatalog] = react.useState(null);
	const [pending, setPending] = react.useState(null);
	const [failure, setFailure] = react.useState("");
	const [expanded, setExpanded] = react.useState(false);
	const readId = react.useRef(0);
	const writeChain = react.useRef(Promise.resolve());
	const reload = () => {
		const mine = ++readId.current;
		return rpc(RPC.READ_CATALOG).then((result) => {
			if (mine !== readId.current) return;
			setCatalog({
				revision: result?.revision,
				providers: result?.providers ?? []
			});
			setFailure("");
		}, () => {
			if (mine !== readId.current) return;
			setFailure("无法读取模型配置");
		});
	};
	react.useEffect(() => {
		reload();
	}, [providerId, invalidations]);
	const row = catalog === null ? void 0 : catalog.providers.find((entry) => entry.provider === providerId);
	const keyOf = (modelId) => `${providerId}::${modelId}`;
	const isBusy = (model) => pending !== null && pending[keyOf(model.id)] === true;
	const toggle = (model) => {
		const next = !model.image;
		setPending((current) => ({
			...current ?? {},
			[keyOf(model.id)]: true
		}));
		setFailure("");
		setCatalog((current) => current === null ? current : {
			revision: current.revision,
			providers: current.providers.map((entry) => entry.provider !== providerId ? entry : {
				provider: entry.provider,
				models: entry.models.map((m) => m.id !== model.id ? m : {
					...m,
					image: next
				})
			})
		});
		const mine = ++readId.current;
		writeChain.current = writeChain.current.then(async () => {
			try {
				await rpc(RPC.SET_IMAGE, {
					provider: providerId,
					modelId: model.id,
					image: next
				});
				await reload();
			} catch (error) {
				if (mine === readId.current) setFailure(error instanceof Error ? error.message : "写入失败");
				await reload();
			} finally {
				setPending((current) => {
					const copy = { ...current ?? {} };
					delete copy[keyOf(model.id)];
					return copy;
				});
			}
		});
	};
	const children = [];
	children.push(react.createElement("div", {
		key: "head",
		className: "dsh-tw-head"
	}, react.createElement("span", { className: "dsh-tw-title" }, "图片输入能力")));
	children.push(react.createElement("p", {
		key: "hint",
		className: "dsh-tw-hint"
	}, "勾选后，模型允许输入图片"));
	if (catalog === null) children.push(react.createElement("p", {
		key: "loading",
		className: "dsh-tw-hint"
	}, "读取中…"));
	else if (row === void 0 || row.models.length === 0) children.push(react.createElement("p", {
		key: "empty",
		className: "dsh-tw-hint"
	}, "这个提供方目前没有手写的模型列表（使用内置目录），无法逐项声明图片能力。"));
	else {
		const models = row.models;
		const collapsedHeight = Math.round(ROW_HEIGHT * VISIBLE_ROWS);
		const overflows = models.length > VISIBLE_ROWS;
		const showAll = expanded || !overflows;
		const rows = models.map((model) => react.createElement("label", {
			key: `row-${model.id}`,
			className: "dsh-tw-row",
			title: model.declaresInput ? "配置中已显式声明 input" : "尚未声明 input（默认纯文本）"
		}, [
			react.createElement("input", {
				key: "cb",
				type: "checkbox",
				checked: model.image,
				disabled: isBusy(model),
				onChange: () => toggle(model)
			}),
			react.createElement("span", {
				key: "id",
				className: "dsh-tw-id"
			}, model.name.length > 0 ? `${model.name} (${model.id})` : model.id),
			model.contextWindow === null ? null : react.createElement("span", {
				key: "cap",
				className: "dsh-tw-cap"
			}, `${model.contextWindow} ctx`),
			isBusy(model) ? react.createElement("span", {
				key: "p",
				className: "dsh-tw-cap"
			}, "保存中…") : null
		]));
		const listChildren = [react.createElement("div", {
			key: "list",
			className: "dsh-tw-list",
			style: showAll ? void 0 : { height: `${collapsedHeight}px` }
		}, rows)];
		if (!showAll) listChildren.push(react.createElement("div", {
			key: "mask",
			className: "dsh-tw-mask"
		}));
		children.push(react.createElement("div", {
			key: "wrap",
			className: "dsh-tw-listWrap"
		}, listChildren));
		if (overflows) children.push(react.createElement("button", {
			key: "toggle",
			type: "button",
			className: "dsh-tw-toggle",
			onClick: () => setExpanded((v) => !v)
		}, [react.createElement("span", { key: "t" }, expanded ? "收起" : `展开全部 ${models.length} 个模型`), react.createElement("span", {
			key: "i",
			className: "dsh-tw-chevron",
			style: expanded ? { transform: "rotate(180deg)" } : void 0
		}, react.createElement(_deepseek_ai_dsh_client_ui_primitives.IconChevronDownOutline14, {}))]));
	}
	if (failure.length > 0) children.push(react.createElement("div", {
		key: "err",
		className: "dsh-tw-err"
	}, failure));
	return react.createElement("div", { "data-dsh-tweaks-image": providerId }, children);
}
function PersonalizationSection({ invalidations }) {
	useInvalidationVersion(invalidations);
	const [saved, setSaved] = react.useState(null);
	const [draft, setDraft] = react.useState("");
	const [status, setStatus] = react.useState("");
	const [failure, setFailure] = react.useState("");
	const [busy, setBusy] = react.useState(false);
	const readId = react.useRef(0);
	const editing = react.useRef(false);
	react.useEffect(() => {
		const mine = ++readId.current;
		rpc(RPC.READ_INSTRUCTION).then((result) => {
			if (mine !== readId.current) return;
			const text = String(result?.text ?? "");
			setSaved(text);
			if (!editing.current) setDraft(text);
			setFailure("");
		}, () => {
			if (mine === readId.current) setFailure("无法读取设置");
		});
	}, [invalidations]);
	const commit = async () => {
		if (saved === null || draft === saved || busy) return;
		setBusy(true);
		setFailure("");
		try {
			await rpc(RPC.WRITE_INSTRUCTION, { text: draft });
			setSaved(draft);
			setStatus(draft.trim().length === 0 ? "已清空（不再注入）" : `已更新 ${draft.length} 字符`);
		} catch (error) {
			setFailure(error instanceof Error ? error.message : "写入失败");
		} finally {
			setBusy(false);
		}
	};
	return react.createElement("div", { "data-dsh-tweaks-personalization": "1" }, [
		react.createElement("div", {
			key: "title",
			className: "dsh-tw-title"
		}, "系统指令"),
		react.createElement("div", {
			key: "hint",
			className: "dsh-tw-hint"
		}, "作为最通用的系统指令，注入每次对话上下文的最开头（身份说明之后、所有工具与策略说明之前）。离开输入框即自动保存；留空则不注入。"),
		react.createElement("textarea", {
			key: "ta",
			className: "dsh-tw-textarea",
			value: draft,
			disabled: busy,
			spellCheck: false,
			placeholder: "例如：始终用中文回答；先给结论再给理由；不要奉承，直接指出我的错误。",
			onChange: (event) => {
				editing.current = true;
				setDraft(event.target.value);
				setStatus("");
			},
			onBlur: () => {
				editing.current = false;
				commit();
			}
		}),
		react.createElement("div", {
			key: "st",
			className: "dsh-tw-status"
		}, busy ? "保存中…" : status.length > 0 ? status : saved !== null && draft !== saved ? "有未保存的改动（离开输入框时保存）" : ""),
		failure.length > 0 ? react.createElement("div", {
			key: "err",
			className: "dsh-tw-err"
		}, failure) : null
	]);
}
/**
* A plain (non-hook) invalidation source: a version number plus a subscriber
* set, owned by the plugin fiber.
*
* `apply()` runs once at activation, outside any React render, so it cannot
* call hooks — this is a store the components subscribe to instead. It bumps
* on every signal that can move the settings document underneath the panels.
*
* `settings/document-updated` is a forwarded Host event: it sits on the
* `API_REMOTE_FORWARDED_EVENTS` allowlist, which is also the legal key set of
* `ctx.remote.$on`. `connection/reset` is the local reconnect signal the
* settings mirror refreshes on.
*
* Both subscriptions are optional by construction: a static bundle whose
* composition lacks `remote` must still mount and simply never refresh. A
* missing listener is a stale panel; a throw here would be a failed plugin.
*/
function createInvalidationSource(ctx) {
	let version = 0;
	const listeners = /* @__PURE__ */ new Set();
	const notify = () => {
		version += 1;
		for (const listener of [...listeners]) listener();
	};
	const disposers = [];
	const remote = ctx?.remote;
	if (remote !== void 0 && typeof remote.$on === "function") try {
		disposers.push(remote.$on("settings/document-updated", notify));
	} catch {}
	if (typeof ctx?.on === "function") try {
		disposers.push(ctx.on("connection/reset", notify));
	} catch {}
	return {
		subscribe: (listener) => {
			listeners.add(listener);
			return () => listeners.delete(listener);
		},
		getVersion: () => version,
		dispose: () => {
			for (const dispose of disposers) dispose();
			listeners.clear();
		}
	};
}
/** Subscribe one component to the invalidation source. */
function useInvalidationVersion(source) {
	return react.useSyncExternalStore(source.subscribe, source.getVersion, source.getVersion);
}
const inject = ["slots", "remote"];
function apply(ctx) {
	const slots = ctx.get("slots");
	if (slots === void 0) return;
	/**
	* One invalidation source for both panels: a slot component is re-created on
	* every render, so a subscription inside one would leak a listener per
	* render. One store owned by this fiber feeds every mounted panel instead.
	*/
	const invalidations = createInvalidationSource(ctx);
	ctx.effect(() => invalidations.dispose, "dsh-tweaks: invalidation subscriptions");
	ctx.effect(() => insertStyles([
		"[data-dsh-tweaks-image]{border:.5px solid var(--dsw-alias-border-l4);border-radius:16px;padding:12px 14px;margin-top:12px;font-size:var(--dsh-content-font-size-secondary,13px)}",
		"[data-dsh-tweaks-image] .dsh-tw-head{display:flex;align-items:center;justify-content:space-between;gap:8px}",
		"[data-dsh-tweaks-image] .dsh-tw-title{font-weight:600;color:var(--dsw-alias-label-primary)}",
		"[data-dsh-tweaks-image] .dsh-tw-hint{color:var(--dsw-alias-label-tertiary);line-height:18px;margin:4px 0 0}",
		"[data-dsh-tweaks-image] .dsh-tw-listWrap{position:relative;margin-top:8px}",
		"[data-dsh-tweaks-image] .dsh-tw-list{overflow:hidden}",
		"[data-dsh-tweaks-image] .dsh-tw-mask{position:absolute;left:0;right:0;bottom:0;height:22px;pointer-events:none;background:linear-gradient(to bottom,transparent,var(--dsw-alias-bg-module-platform,var(--dsw-alias-bg-base,transparent)))}",
		"[data-dsh-tweaks-image] .dsh-tw-row{display:flex;align-items:center;gap:8px;padding:5px 0;cursor:pointer;height:32px;box-sizing:border-box}",
		"[data-dsh-tweaks-image] .dsh-tw-id{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--dsw-alias-label-primary)}",
		"[data-dsh-tweaks-image] .dsh-tw-cap{flex:none;color:var(--dsw-alias-label-tertiary);font-variant-numeric:tabular-nums}",
		"[data-dsh-tweaks-image] .dsh-tw-row input{flex:none;margin:0;cursor:pointer}",
		"[data-dsh-tweaks-image] .dsh-tw-row input:disabled{cursor:progress}",
		"[data-dsh-tweaks-image] .dsh-tw-toggle{margin-top:8px;width:100%;background:none;border:none;color:var(--dsw-alias-label-secondary);font:inherit;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:6px;padding:4px 0}",
		"[data-dsh-tweaks-image] .dsh-tw-toggle:hover{color:var(--dsw-alias-label-primary)}",
		"[data-dsh-tweaks-image] .dsh-tw-chevron{display:inline-flex;transition:transform 120ms ease}",
		"[data-dsh-tweaks-image] .dsh-tw-err{color:var(--dsw-alias-state-error-primary);margin-top:8px}",
		"[data-dsh-tweaks-personalization]{display:flex;flex-direction:column;gap:10px;width:100%;padding:4px 0}",
		"[data-dsh-tweaks-personalization] .dsh-tw-title{font-weight:600;font-size:14px;color:var(--dsw-alias-label-primary)}",
		"[data-dsh-tweaks-personalization] .dsh-tw-hint{color:var(--dsw-alias-label-tertiary);line-height:18px;font-size:var(--dsh-content-font-size-secondary,13px)}",
		"[data-dsh-tweaks-personalization] .dsh-tw-textarea{width:100%;min-height:180px;box-sizing:border-box;resize:vertical;overflow:auto;padding:10px 12px;border-radius:16px;border:.5px solid var(--dsw-alias-border-l4);background:transparent;color:var(--dsw-alias-label-primary);font:inherit;line-height:20px;display:block}",
		"[data-dsh-tweaks-personalization] .dsh-tw-textarea:hover{border-color:var(--dsw-alias-label-tertiary)}",
		"[data-dsh-tweaks-personalization] .dsh-tw-textarea:focus{outline:none;border-color:var(--dsw-alias-label-secondary)}",
		"[data-dsh-tweaks-personalization] .dsh-tw-status{color:var(--dsw-alias-label-tertiary);font-size:var(--dsh-content-font-size-secondary,13px);min-height:18px}",
		"[data-dsh-tweaks-personalization] .dsh-tw-err{color:var(--dsw-alias-state-error-primary);font-size:var(--dsh-content-font-size-secondary,13px)}"
	].join("\n")));
	slots.inject("settings.models.provider-card", () => slots.register({
		name: "settings.models.provider-card",
		key: LLM_PI_AI_NS
	}, (props) => react.createElement(ImageInputPanel, {
		providerId: props?.provider?.provider ?? "",
		invalidations
	})));
	slots.inject("settings.section", () => slots.register({
		name: "settings.section",
		id: SYSTEM_INSTRUCTION_SECTION_ID,
		order: 5,
		label: "个性化"
	}, () => react.createElement(PersonalizationSection, { invalidations })));
}
//#endregion
exports.apply = apply;
exports.inject = inject;

    return module.exports;
  }
});
