/**
 * Seat the built client half in the web app's module-loader envelope.
 *
 * `dsh-client-modules` serves `lib/client.js` verbatim and then requires the
 * file to have registered itself through `window.__ModuleLoader__.load`. A
 * bundler emits bare CJS, so this step adds the envelope — the same shape
 * every first-party `@deepseek-ai/dsh-client-*` bundle ships:
 *
 *   window.__ModuleLoader__.load({ id, factory: (require) => { … return module.exports; } });
 *
 * The loader calls `factory(require)` once and memoizes its return value as
 * the module's exports, so `module.exports` must be returned explicitly.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { name } = require('../package.json');

const target = new URL('../lib/client.js', import.meta.url);
const code = readFileSync(target, 'utf8');

if (code.includes('__ModuleLoader__.load')) {
  console.log(`wrap-client: lib/client.js is already wrapped for "${name}"`);
  process.exit(0);
}

const banner = [
  `/* ${name} client bundle — generated by scripts/wrap-client.mjs */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  '',
].join('\n');

const footer = ['', '    return module.exports;', '  }', '});', ''].join('\n');

writeFileSync(target, banner + code + footer);
console.log(`wrap-client: wrapped lib/client.js as "${name}"`);
